% =============================================================
%%                          Print the Parameters from DiagModel to Spreadsheet
%
%  2020-07-15        Revised to include HMC                            Jack Geary Murphy  (Princeton Univ)
%  2021-02-07        Revised to include prim dolo & diag mineral   Jack Geary Murphy  (Princeton Univ)
%
% =============================================================

% Put in the path to your folder here ... 
path = '...';

vars = {'Date', ...
    'Time', ...
    'M', ... 
    'Kd_Li', ...
    'Kd_Sr', ...
    'alpha_Li', ...
    'PrimArag_%',...
    'PrimLMC_%',...
    'PrimHMC_%',...
    'PrimDolo_%',...
    'PrimArag_Li',...
    'PrimLMC_Li',...
    'PrimHMC_Li',...
    'PrimDolo_Li',...
    'PrimArag_dLi', ...
    'PrimLMC_dLi', ...
    'PrimHMC_dLi', ...
    'PrimDolo_dLi', ...
    'PrimFluid_Li', ...
    'PrimFluid_dLi', ...
    'Arag_dCa', ...
    'Arag_dMg', ...
    'Arag_dC', ...
    'Arag_dO',...
    'Arag_dSr', ...
    'LMC_dCa', ...
    'LMC_dMg', ...
    'LMC_dC', ...
    'LMC_dO',...
    'LMC_dSr', ...
    'HMC_dCa', ...
    'HMC_dMg', ...
    'HMC_dC', ...
    'HMC_dO',...
    'HMC_dSr', ...
    'Dolo_dCa', ...
    'Dolo_dMg', ...
    'Dolo_dC', ...
    'Dolo_dO',...
    'Dolo_dSr', ...
    'Fluid_Ca',...
    'Fluid_Mg',...
    'Fluid_C',...
    'Fluid_Sr',...
    'Fluid_dCa',...
    'Fluid_dMg',...
    'Fluid_dC', ...
    'Fluid_dO',...
    'Fluid_dSr', ...
    'alpha_Ca',...
    'alpha_Mg',...
    'alpha_C',...
    'alpha_O',...
    'alpha_Sr',...
    'advect_rate',...
    'react_rate_arag',...
    'react_rate_HMC',...
    'react_rate_LMC',...
    'react_rate_dolo',...
    'react_rate_DIAG',...
    'time',...
    'box'};

rundate = {datestr(now, 'yyyy-mm-dd')};
runtime = {datestr(now, 'HH:MM')}; 

T = table(rundate, ...
runtime, ...
M,...
tune.J, ...
tune.L, ...
tune.K, ...
Aragonite, ...
LMC, ...
HMC, ...
Dolomite, ...
tune.A, ...
tune.B, ...
tune.C, ...
tune.D, ...
tune.G, ...
tune.E, ...
tune.F, ...
tune.M, ...
tune.H, ...
tune.I, ...
Solid.arag.dCa, ...
Solid.arag.dMg,...
Solid.arag.dC,...
Solid.arag.dO,...
Solid.arag.dSr,...
Solid.LMC.dCa,...
Solid.LMC.dMg, ...
Solid.LMC.dC, ...
Solid.LMC.dO,...
Solid.LMC.dSr, ...
Solid.HMC.dCa, ...
Solid.HMC.dMg,...
Solid.HMC.dC, ...
Solid.HMC.dO, ...
Solid.HMC.dSr,...
Solid.dolo.dCa, ...
Solid.dolo.dMg,...
Solid.dolo.dC, ...
Solid.dolo.dO, ...
Solid.dolo.dSr,...
Ca_fluid, ...
Mg_fluid,...
C_fluid, ...
Sr_fluid, ...
Fluid.dCa(1), ...
Fluid.dMg(1), ...
Fluid.dC(1), ...
Fluid.dO(1), ...
Fluid.dSr(1), ...
alpha.Ca, ...
alpha.Mg, ...
alpha.C, ...
alpha.O,...
alpha.Sr, ...
u, ...
R.arag, ...
R.HMC, ...
R.LMC, ...
R.dolo, ...
R.DIAG, ...
time, ...
box,...
'VariableNames', vars);
writetable(T,[path, datestr(now, 'yyyy-mm-dd (HH|MM)'), '.xlsx']);
